### ISSUE TITLE
Update the pdf files

### ISSUE THREAD

**Issue by gaspardcereza** [jcohenadad/GBM8378#10]
Some pdf files still refer to Matlab functions and other obsolete stuff. 
We need to check all of them to be consistent with the new versions of the labs.

**Comment by gaspardcereza** [comment]
We decided to put the pdf files on moodle and just keep the notebooks and related files here.

**Comment by po09i** [comment]
PDF were updated on moodle and on the drive

**Comment by gaspardcereza** [comment]
Updated versions of the PDF files are available in the lab's google drive.
