### ISSUE TITLE
Créer lab intro à Python

### ISSUE THREAD

**Issue by jcohenadad** [jcohenadad/GBM8378#2]
Il existe beaucoup de ressources/tuto sur le net. Le but est de trouver la bonne et la faire pendant le lab. Lister les bons tutos ici, et on fera une sélection plus tard. 

* [w3schools](https://www.w3schools.com/python/)

Les apprentissages prérequis sont :
- python in general : installation, import, etc.
- jupyter notebook : Markdown, notebook, Environnement, ajouter une image, equation en latex.., 
- scientific libs (numpy, scipy, nibabel)
- Ajouter quelaue chose pour encourager la prise d’intiative et d’autonomy (type coder exprès un bug pour les faire aller chercher dans la doc) 
- Diffference fft(X,[],1) , fft2(X), fft(X).

**Comment by po09i** [comment]
À ajouter :

```
# <font color='coral'> Autres ressources </font>

<div class="alert alert-block alert-info">
Pour écrire les réponse vous pouvez regarder:<ul> <a href="https://support.squarespace.com/hc/fr-fr/articles/206543587-Aide-m%C3%A9moire-Markdown">Markdown basic</a> <br>
<a href="https://github.com/cben/mathdown/wiki/math-in-markdown ">math in markdown</a>
<br>
    Vous pouvez introduire des équation en latex dont l'utilisation est détaillé <a href="https://en.wikibooks.org/wiki/LaTeX/Mathematics ">ici</a> 
    <br></ul>
</div>
```
