### ISSUE TITLE
Porter lab 1 (CT) vers Python

### ISSUE THREAD

**Issue by jcohenadad** [jcohenadad/GBM8378#3]
Notes de 2020:
- explication sur les 1000 fois X photons pour le bruit : ce la ne semble pas clair en terme d’interpretation physique pour les étudiants.
- Ajouter code angle pas constant. Precisez le fait de reutiliser le code au dessus. 
- Regarder question theorem tranche centrale

**Comment by gaspardcereza** [comment]
Concernant le passage des variables (ici sinogramme.mat) de matlab vers python, j'ai trouvé 3 solutions présentant toutes des avantages et des inconvénients: 

### Option 1: Construire le sinogramme à partir d'un fantôme Shepp-Logan 
C'est l'option choisie par Guillaume dans son adaptation du TP. 
* Pros: 
   - Solution élégante qui ne nécessite pas de fichier 'sinogramme.mat'
* Cons: 
   - Nécessite l'utilisation de skimage pour charger le fantôme et effectuer la transformée de radon > Augmente le nombre de fonctions à fournir aux étudiants, ce qui peut être un peu confusant pour eux.
   - Ne fonctionne que pour un fantôme disponible sur skimage (suffisant dans notre cas mais pas généralisable a un sinogramme quelconque qu'un ingénieur pourrait avoir à traiter).
   - **Le sinogramme est différent** de celui fourni habituellement.



### Option 2: Utiliser un fichier 'sinogramme'.
Le fichier est juste une conversion en objet python du fichier de 2020
* Pros:
   - Cela me semble être la solution la plus simple et compréhensible:
```python
with open('sinogramme', 'rb') as file:
    sino_ES_C = pickle.load(file)
```
* Cons:
   - Nécessite pickle pour charger l'objet (pas vraiment problématique en soi).

### Option 3: Conserver le fichier '.mat'
Le fichier en question est le même que pour le lab 2020.
* Pros:
   - Permet aux étudiants de voir comment ouvrir un fichier `.mat` sous Python (scipy.io.loadmat), ce qui peut leur être utile.
* Cons:
   - Cela peut paraître étrange de charger un fichier '.mat' sous python.
   - la fonction peut paraître assez complexe pour un novice sur python: 
```python
sino_ES_C = scipy.io.loadmat('sinogramme.mat',variable_names='R',appendmat=True).get('R')
```

J'ai implémenté/adapté toutes les solutions donc dites moi laquelle vous semble la plus intéressante (et si vous voyez d'autres pros/cons) @po09i @jcohenadad.

**Comment by jcohenadad** [comment]
je vote pour option 1 🥇 

commentaire sur les cons:
> Nécessite l'utilisation de skimage pour charger le fantôme et effectuer la transformée de radon > Augmente le nombre de fonctions à fournir aux étudiants, ce qui peut être un peu confusant pour eux.

ils sont grands, ils vont se debrouiller 😊 

> Ne fonctionne que pour un fantôme disponible sur skimage (suffisant dans notre cas mais pas généralisable a un sinogramme quelconque qu'un ingénieur pourrait avoir à traiter.

🤔 pas sûr de comprendre...   si ils remplacent le shepp logan par une autre image, ils peuvent utiliser la transfo de radon pareil, right?

> Le sinogramme est différent de celui fourni habituellement.

eh ben on change les habitudes, problem solved 😉
